### ISSUE TITLE
Facebook  + Twitter Share Counter Not Working

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman-addons#21]
May be due to change in Facebook API
https://wordpress.org/support/topic/share-social-buttons-not-working

**Comment by Nikeo** [comment]
Also reported here : https://wordpress.org/support/topic/facebook-share-counter-is-0/

**Comment by Nikeo** [comment]
Edit : According to this forum thread, twitter count is not working as well
https://wordpress.org/support/topic/share-buttons-for-facebook-and-twitter-show-a-count-of-0/

**Comment by Nikeo** [comment]
possible FB fix here https://github.com/Julienh/Sharrre/pull/296/files

**Comment by goodbytes-gb** [comment]
Twitter was still broken for me, in sharrre.jquery.min the count variable for Twitter is set to false... it's not counting by design.. I'm not sure why Hueman isn't enabling count by default from within the options.. however several attempts to enable count failed so I was forced to manually update line `290`: to `count: false,`.

Also, http://opensharecount.com fails to load on my WP site with forced https:// due to mixed content... it really should be protocol independent by updating line `306` to `return "//opensharecount.com/count.json?url={url}";`

**Comment by Nikeo** [comment]
OK thanks for the feedback @goodbytes-gb . 
I'm still on it then

**Comment by Raikia** [comment]
Yep, twitter still is broken for me and just shows 0 even though when I pull the actual "opensharecount.com" page it says the counter is above 0.

**Comment by Raikia** [comment]
@Nikeo The twitter count is still broken, but it actually looks like its not even calling out to opensharecount.com.  I ran it through burp proxy and this is what it shows:

![Image](http://i.imgur.com/lBpDHAY.png)

The arrow shows that it is correctly calling out to LinkedIn, but you can see there is no request to opensharecount.com for the twitter button.

Link to site is here: https://raikia.com/first-couple-of-tools/

**Comment by denzelchia** [comment]
Hi @Nikeo 

Please refer to the following support thread on WordPress.org
https://wordpress.org/support/topic/social-media-counters/

Seems like twitter share count is not working.
I cannot confirm this, as I do not have the means to do a test, because I don't have an online Hueman Theme test site.

Thank you
