### ISSUE TITLE
Notice: Use of undefined constant STYLESHEETPATH – assumed ‘STYLESHEETPATH

### ISSUE THREAD

**Issue by ghost** [presscustomizr/hueman-addons#46]
https://wordpress.org/support/topic/use-of-undefined-constant-stylesheetpath/#post-9981380

> Today after last update of Hueman Addons several times happened: “Notice: Use of undefined constant STYLESHEETPATH – assumed ‘STYLESHEETPATH’ in /www/wp-includes/theme.php on line 136”
> I hope everything is alright 🙂

Hi @eri-trabiccolo let me know if you can reproduce the problem on your side ?

**Comment by eri-trabiccolo** [comment]
No I can't :/
What I can reproduce is a fatal error log previewing a different theme:
`[16-Feb-2018 12:15:32 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function hu_get_raw_option() in /srv/www/customizr-tests/public_html/wp-content/plugins/hueman-addons/addons/skop/czr-skop.php:2039`

But the above is an "old" problem with ha_isprevdem, as far as I remember.

**Comment by eri-trabiccolo** [comment]
so the issue reported by the user happen in wp-includes/theme.php is_child_theme()
and yes, **always** happens using a child-theme.
Did not happen with the previous version of hu_isprevdem:
https://github.com/presscustomizr/hueman-addons/blob/v2.0.14/addons/ha-init.php#L388

and doesn't not happen in hueman with basically the same current function.

Honestly this seems to be more a WP "issue" which accesses to contants not yet defined.

Actually this:
a)
`ha_get_raw_option( 'template', null, false ) != get_stylesheet() && ! is_child_theme()`
should be:
b)
`ha_get_raw_option( 'template', null, false ) != get_template()`

because b), when using a child-theme already addresses you're previewing the same theme( template ).

Right?

**Comment by ghost** [comment]
yes b) makes sense.
needs to be tested
Thank you for the quick feedback :)

**Comment by eri-trabiccolo** [comment]
I tested it locally and seemed to be fine.
Moreover: we don't really need to change that function in the themes where we really dont' want to risk to mess the prevdem (for wp.org preview), because that function is fired by the themes, when both TEMPLATEPATH and STYLESHEETPATH constants are surely defined.

**Comment by signaleleven** [comment]
I am also observing this problem, only with a child theme, and removing the call to is_child_theme() (option b) above) seems to fix it.

I am not familiar with plugin development, so I don't really understand what is the way forward here.
